[package]
name = "crypto_app_with_fips"
version = "0.1.0"
edition.workspace = true

[dependencies]
some_crypto_lib = { path = "../some_crypto_lib" }
aws-lc-rs = { workspace = true, features = ["fips"] }